---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-virt-cloudeka-ai-v1alpha1-cloudekamachine
  failurePolicy: Fail
  name: mcloudekamachine.kb.io
  rules:
  - apiGroups:
    - virt.cloudeka.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cloudekamachines
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-virt-cloudeka-ai-v1alpha1-cloudekamachine
  failurePolicy: Fail
  name: vcloudekamachine.kb.io
  rules:
  - apiGroups:
    - virt.cloudeka.ai
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - cloudekamachines
  sideEffects: None
