# permissions for end users to view cloudekamachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cloudekamachine-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudekamachine-viewer-role
rules:
- apiGroups:
  - cloudeka.ai.cloudeka.ai
  resources:
  - cloudekamachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudeka.ai.cloudeka.ai
  resources:
  - cloudekamachines/status
  verbs:
  - get
