# permissions for end users to edit cloudekamachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cloudekamachine-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudekamachine-editor-role
rules:
- apiGroups:
  - virt.cloudeka.ai
  resources:
  - cloudekamachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - virt.cloudeka.ai
  resources:
  - cloudekamachines/status
  verbs:
  - get
