# permissions for end users to view cloudekadatavolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cloudekadatavolume-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudekadatavolume-viewer-role
rules:
- apiGroups:
  - virt.cloudeka.ai
  resources:
  - cloudekadatavolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - virt.cloudeka.ai
  resources:
  - cloudekadatavolumes/status
  verbs:
  - get
