---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cloudeka.ai.cloudeka.ai
  resources:
  - cloudekamachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloudeka.ai.cloudeka.ai
  resources:
  - cloudekamachines/finalizers
  verbs:
  - update
- apiGroups:
  - cloudeka.ai.cloudeka.ai
  resources:
  - cloudekamachines/status
  verbs:
  - get
  - patch
  - update
