apiVersion: api.cloudeka.ai/v1beta1
kind: VirtualMachine
metadata:
  labels:
    app.kubernetes.io/name: virtualmachine
    app.kubernetes.io/instance: virtualmachine-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: virtualmachine-sample
spec:
  # TODO(user): Add fields here
